spring.application.name=IntroductionToSpringBoot
server.port=9000
#debug=true
#deploy.env=production
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/home/mritunjay/Downloads/IntroductionToSpringBoot/db
spring.datasource.username=mritunjayDB
spring.datasource.password=Mritunjay123
spring.jpa.hibernate.ddl-auto=update